### ISSUE TITLE
Remove red coloring on faces which point towards plate.

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#23]
When changing to the Smart Slice tab, faces which point towards the build plate have a red color -  a remnant of the Prepare environment.

We really don't have a need for this yet, and it could be confusing, so we should have all faces be colored the same.

**Comment by thopiekar** [comment]
Actually, it is highlighting the faces, which need are too steep and need support.
![image](https://user-images.githubusercontent.com/1847437/68939765-b077ed00-07a1-11ea-82ae-93d8e839c644.png)

**Comment by thopiekar** [comment]
Found a preference which basically does what we want.
There are two options of improvement at this point:
* When entering the stage, the plugin will change the users settings - it is an option you can set somewhere. We don't want to change this setting, because once the user closes window with our stage open, it will be permanently saved.
* Therefore we either need to introduce our own "SolidView" or we contribute to Cura's SolidView and add an override variable. We could then ask the PluginRegistry for the SolidView and using the plugin's object set the override to True. The user's setting will be kept and we can make the colored face invisible. On the other hand we might need a view anyways, if we want to move the marking of faces to a view.

![image](https://user-images.githubusercontent.com/1847437/68940229-e36eb080-07a2-11ea-800c-8d3e449a5cf8.png)
![image](https://user-images.githubusercontent.com/1847437/68940252-f1243600-07a2-11ea-98e9-3c447a949e3f.png)
