### ISSUE TITLE
Speed up face selection

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#29]
Face selection can lag a bit - need to speed it up

**Comment by bradymadams** [comment]
Face selection speed up implemented in #83. It is very responsive now. There is a one time delay for complex meshes when the Anchor/Load tool is first selected. All edge angles are computed at this time and stored for quick traversal when faces are clicked. I don't think there is any way we'll get around having to perform a heavy mesh computation because of the info any reasonable face detection algorithm would need. However, what we could do is put the computation into a background worker for complex meshes and show the user a progress bar so the UI doesn't freeze up unexpectedly. 

I'll wait to hear feedback if that's something we want for the alpha, or if we want to create a separate issue and address it later.

**Comment by dougkenik** [comment]
We can create a separate ticket for the enhancement. This is good enough for now
