### ISSUE TITLE
Job Fails on Open

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#375]
The attached job (3MF) was ran by a customer and saved. When they opened it, it caused a hard crash. It looks like the projects was saved after a failed run, but I might be wrong.

Let's also add a unit test to catch this scenario.

Reach out to Doug for the file

**Comment by AijunHall** [comment]
> It looks like the projects was saved after a failed run

I've found a way to reproduce this crash, which is along the lines of this, and is probably what the customer did in this situation.

1. Open a new import/project without any previous work done on it so that it has no SmartSlice data
2. Set the anchor, load, and other settings so that it is ready to be validated in the SmartSlice stage 
`SmartSlicePlugin.SmartSliceCloudConnector.status` should be set to `SmartSliceCloudStatus.ReadyToVerify` *
3. Save the project without validating
4. Opening the project 3mf file results in the crash

Heres my Traceback:
```
Traceback (most recent call last):
  File "C:\dev\Cura\cura\CuraApplication.py", line 1063, in event
    return super().event(event)
  File "C:\Users\AijunHall\source\repos\UM\UM\Qt\QtApplication.py", line 464, in event
    event._function_event.call()
  File "C:\Users\AijunHall\source\repos\UM\UM\Event.py", line 218, in call
    self._function(*self._args, **self._kwargs)
  File "C:\Users\AijunHall\source\repos\UM\UM\Signal.py", line 332, in __performEmit
    func(dest, *args, **kwargs)
  File "C:\dev\Cura\plugins\SmartSlicePlugin\stage\SmartSliceScene.py", line 516, in _process_mesh_analysis
    job.callback()
  File "C:\dev\Cura\plugins\SmartSlicePlugin\SmartSliceExtension.py", line 263, in afterSmartSliceNodeInit
    if results.fea_results is not None and results.fea_results.steps != []:
AttributeError: 'NoneType' object has no attribute 'fea_results'
```

**Comment by bradymadams** [comment]
@AijunHall can you test this and check if this was fixed in your PR?

**Comment by AijunHall** [comment]
@bradymadams @dougkenik This file still has a problem that I forgot to mention, thanks for reopening this. It opens without crashing now, but it fails to validate with this error:
```
SmartSlicePlugin.SmartSliceCloudConnector.submitSmartSliceJob [531]: An error occured while sending and receiving cloud job: Error while processing the job:<br>Analysis unexpectedly failed.
```
So now this Issue is that it fails on verification.

**Comment by dougkenik** [comment]
I would imagine tis is connected with #377
