### ISSUE TITLE
Modifier Mesh Is Moved Below the Stage On Cancel Changes

### ISSUE THREAD

**Issue by jake-kirkland-teton** [tetonsim/is-cura-ui#418]
Steps to reproduce:

1) Load an optimized project that has a modifier mesh.
2) On the prepare stage, delete the modifier mesh.
3) Cancel your changes.

[https://app.zenhub.com/files/209108148/3cff0763-5d60-44c7-8b00-6bf504940733/download](https://app.zenhub.com/files/209108148/3cff0763-5d60-44c7-8b00-6bf504940733/download)

![Mod_Mesh_bug.gif](https://images.zenhubusercontent.com/5efa5ada9e19f8d4e56a2b87/3a1c8303-78ec-4c1a-a049-d5b47cc73107)

**Comment by dougkenik** [comment]
@jake-kirkland-teton the first thing we need to ask is why we're prompting the user to cancel or confirm changes when they open this project. Nothing has changed on open, so the project should load without that prompt. I assume this is because we are creating problem meshes as a SmartSliceMeshNode, and by default those are getting tracked in the SmartSliceProperty.SmartSliceScene class, which is causing the SmartSlicePropertyHandler to think there is a change in the scene

**Comment by jake-kirkland-teton** [comment]
That is a bizarre one, and you might be right. Part of the problem is how we cashe and restore information relating to the meshes. I'm almost positive what's going on is we are attaching the modifier mesh that is restored to the root node rather than the printable mesh, which is why it can appear under the build plate.
