### ISSUE TITLE
Disable shadow on bottom of part

### ISSUE THREAD

**Issue by dougkenik** [tetonsim/is-cura-ui#42]
I don't think we need the shadow on the bottom of the part.

**Comment by dougkenik** [comment]
![image](https://user-images.githubusercontent.com/24813209/68971672-4c582780-07a7-11ea-9542-d90ae24f8c2e.png)

**Comment by bradymadams** [comment]
I stumbled upon how this is done in Cura. It's a `Scene.ConvexHullNode` object and after fiddling with it a little bit it doesn't seem to respect the `SceneNode` visibility attribute. The only way I could get it to hide was by setting the mesh data to empty. Hopefully there is a better way because we'd need to revert it outside of the Smart Slice stage.

Anyway, hope that's helpful for whomever handles this issue in the future.
