### ISSUE TITLE
Print Setting Hierarchy Issues with Infill Angles/Infill Pattern during Optimization

### ISSUE THREAD

**Issue by AijunHall** [tetonsim/is-cura-ui#578]
These Scenarios only cause errors during the Optimization. Validation jobs are being respected and going through, but the optimizer is trying to optimize the global print settings vs the mesh print settings.

**Infill Angles**
If a user enters a valid mesh infill angle, but an invalid extruder/global config infill angle then this error is brought up.
![image](https://user-images.githubusercontent.com/54338983/129263271-e3542b9c-721a-4ce4-86e0-0d6e990e0204.png)

**Infill Pattern**
If a user enters a valid mesh infill pattern, but an invalid extruder/global config infill pattern then this generic error is brought up.
![image](https://user-images.githubusercontent.com/54338983/129263552-2daa60ac-3403-41d6-b130-08bf0c8963f2.png)

**Comment by jlselden** [comment]
@AijunHall @dougkenik There are no checks done in the `smartslice` repo for these settings. It simply creates a print config by following the hierarchy. I believe all these checks happen in `pywim.smartslice.val`, but I'm not seeing where that error message "Only 1 infill angle..." would be generated in that module.

**Comment by dougkenik** [comment]
@jlselden the error is being generated in wim. It's odd that these jobs pass through validation just fine, but not optimization. For the optimization, are you just grabbing the global settings and ignoring mesh level settings?

**Comment by jlselden** [comment]
> @jlselden the error is being generated in wim. It's odd that these jobs pass through validation just fine, but not optimization. For the optimization, are you just grabbing the global settings and ignoring mesh level settings?

Not quite. For optimization, I'm using the extruder -> global part of the hierarchy to determine the print config. So if the crucial settings are in the mesh, it looks like I'll miss them unless they are also being optimized. Infill angles and pattern would be missed. This doesn't happen for validation, but that's because we allow modifier meshes and the full hierarchy is employed.

This was an oversight on my part, but should be an easy fix. I'll move this issue to the `smartslice` repo.

**Comment by dougkenik** [comment]
Thank you!

**Comment by jlselden** [comment]
I can't close this issue, but it's now redundant.
