### ISSUE TITLE
Modifier mesh incorrectly counted as a printable mesh

### ISSUE THREAD

**Issue by bradymadams** [tetonsim/is-cura-ui#96]
Occasionally, after a successful optimization, the addition of modifier meshes is seen as a new printable node by the plugin and it kicks the user back to the Prepare stage.

This is probably a race condition and might be related to #95. I'd suggest we handle #95 first and then see if this problem still occurs.

**Comment by rickdalgarno** [comment]
This issue is difficult to test conclusively. Brady and I agreed to run a few optimizations and see if this issue comes up. I ran the pedal fixture and simple brake lever through optimizations and generated mod meshes in both cases. After optimization was complete, Cura remained in the Smart Slice stage. It did not automatically switch to the Prepare stage. Tested with Cura 4.4.1 and SmartSlicePlugin-r20.1.2.
